# Generated by Django 2.2.2 on 2019-06-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190627_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogpost',
        ),
    ]
